#!/bin/bash

# 🚀 QUICK START SCRIPT - Setup Database & Admin Panel

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  📦 NGỌC NHẤT LINH - Admin Panel & Database Setup               ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "✅ Environment Setup"
echo "   • .env.local created with Supabase credentials"
echo "   • @supabase/supabase-js already installed"
echo ""

echo "📋 Next Steps:"
echo ""
echo "1️⃣  CREATE DATABASE TABLE"
echo "   Go to: https://app.supabase.com"
echo "   Project: lwshqypvoockvejpwmhk"
echo "   Section: SQL Editor → New Query"
echo "   Copy-paste code from: SUPABASE_SETUP.sql"
echo "   Click: RUN ✓"
echo ""

echo "2️⃣  START DEVELOPMENT SERVER"
echo "   Run: npm run dev"
echo "   Opens: http://localhost:3000"
echo ""

echo "3️⃣  ACCESS ADMIN PANEL"
echo "   Navigate to: http://localhost:3000/admin"
echo "   Or click 'Admin' in the navbar"
echo ""

echo "4️⃣  ADD YOUR FIRST PRODUCT"
echo "   • Click 'Thêm Sản phẩm' button"
echo "   • Fill in: Name, Description, Price, Category, Image URL"
echo "   • Click 'Thêm' to save"
echo "   • Product appears in dashboard + /products page"
echo ""

echo "5️⃣  VIEW PRODUCTS"
echo "   Navigate to: http://localhost:3000/products"
echo "   Products sync automatically from database! 🎉"
echo ""

echo "6️⃣  DEPLOY TO VERCEL"
echo "   Dashboard: https://vercel.com/toanpd292-2055s-projects/ph-m-c-to-n"
echo "   Settings → Environment Variables"
echo "   Add:"
echo "     • VITE_SUPABASE_URL = https://lwshqypvoockvejpwmhk.supabase.co"
echo "     • VITE_SUPABASE_ANON_KEY = sb_publishable_dnJfTrrI0l68nbhuN9jgYg_45yTT5zx"
echo "   Redeploy: Deployments → ... → Redeploy"
echo "   Access: https://ph-m-c-to-n.vercel.app/admin"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "📊 ADMIN PANEL FEATURES"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "✨ Features Included:"
echo "   ✓ Add/Edit/Delete Products"
echo "   ✓ Real-time Image Preview"
echo "   ✓ Category Management"
echo "   ✓ Price Management"
echo "   ✓ Complete Product Info (Name, Description, Category, etc.)"
echo "   ✓ Responsive Design (Works on Mobile & Desktop)"
echo "   ✓ Dark Theme UI"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "📁 FILES CREATED/MODIFIED"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "✅ New Files:"
echo "   • .env.local (Supabase environment variables)"
echo "   • src/pages/Admin.tsx (Complete admin panel component)"
echo "   • SUPABASE_SETUP.sql (SQL schema script)"
echo "   • ADMIN_SETUP_GUIDE.md (Full setup documentation)"
echo "   • QUICK_START.sh (This file!)"
echo ""

echo "✏️  Modified Files:"
echo "   • src/components/Navbar.tsx (Added Admin link)"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "🔧 TROUBLESHOOTING"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "❌ Admin page doesn't load data?"
echo "   → Check browser console (F12) for errors"
echo "   → Verify Supabase table exists in Dashboard"
echo "   → Check .env.local variables are set"
echo ""

echo "❌ Images not showing?"
echo "   → Use valid image URLs (https://...)"
echo "   → Try placeholder: https://via.placeholder.com/300"
echo "   → Upload via Supabase Storage or Cloudinary/ImgBB"
echo ""

echo "❌ Products not showing in /products page?"
echo "   → Check that products are saved in Admin Panel"
echo "   → Refresh page (Ctrl+R or Cmd+R)"
echo "   → Check Supabase table for data"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "🎯 You're All Set! 🎉"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "Run: npm run dev"
echo "Then visit: http://localhost:3000/admin"
echo ""
echo "Happy selling! 🛍️✨"
echo ""
